### ISSUE TITLE
global_ban

### ISSUE THREAD

**Issue by ungenickt-de** [ElNelyo/ElNelyo#1]
Hey is your Global Ban system still Avaible? (https://github.com/ElNelyo/global_ban) I want to use it in my Anticheat and a global ban system would be a great addition to it.

Or is the API Open Source?

**Would be cool if i get an awnser from you! Have a good day. @ElNelyo**

**Comment by ElNelyo** [comment]
Hi @ungenickt-de 
The project is still available but not maintained.

**Comment by ungenickt-de** [comment]
Ah, because its saying "[   script:global_ban] [GB] API is probably down : code error 401"

Can i download the API somewhere? So i can put it on my own Server or something?

**Comment by ungenickt-de** [comment]
@ElNelyo You here?
